name: DVC CI Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Pull Dataset
      run: |
        dvc pull

    - name: Run DVC Pipeline
      run: |
        dvc repro

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model/model.keras
    
    - name: Upload MLflow Logs
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-logs
        path: mlruns/

    - name: Deploy Model to S3
      run: |
        aws s3 cp model/model.keras s3://YOUR_BUCKET_NAME/production-model/model.keras
    
    